package com.fernandowirtz.reportsexample;

import com.fernandowirtz.reportsexample.dao.Customer;
import com.fernandowirtz.reportsexample.reports.ReportService;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JList;

/**
 *
 * @author Gonzalo
 */
public class MainFrame extends javax.swing.JFrame {

    private static final String REPORT_PATH = "/reports/reporteSakila1.jrxml";

    private final ReportService reportService;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        Properties prop = new Properties();
        try {
            prop.load(MainFrame.class.getClassLoader().getResourceAsStream("config.properties"));
        } catch (IOException ex) {
            ex.printStackTrace();
            this.dispose();
        }

        reportService = new ReportService(
                prop.getProperty("dburl"),
                prop.getProperty("dbuser"),
                prop.getProperty("dbpassword")
        );

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewAndSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listEmail = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnViewAndSave.setText("View and Save");
        btnViewAndSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAndSaveActionPerformed(evt);
            }
        });

        listEmail.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listEmail.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listEmailValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listEmail);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewAndSave, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(btnViewAndSave)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewAndSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAndSaveActionPerformed
        if (listEmail.isSelectionEmpty()) {
            return;
        }
        Customer c = listEmail.getSelectedValue();
        int idCliente = c.getId();

        SavePdfChooser chooser = new SavePdfChooser(this);
        String dest = chooser.getFilePath();
        if (dest == null) {

            return;
        }

        Map<String, Object> params = new HashMap<>();
        params.put("ID_CLIENTE", idCliente);

        try {
            reportService.get(REPORT_PATH, params).view();
            reportService.get(REPORT_PATH, params).toPdf(dest, true);
        } catch (Exception ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnViewAndSaveActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        reportService.cargarEmail(listEmail);
       
        btnViewAndSave.setEnabled(false);


    }//GEN-LAST:event_formWindowOpened

    private void listEmailValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listEmailValueChanged

        if (listEmail.isSelectionEmpty()) {
          
            btnViewAndSave.setEnabled(false);
        } else {
           
            btnViewAndSave.setEnabled(true);
        }

    }//GEN-LAST:event_listEmailValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }

 

    public JButton getBtnViewAndSave() {
        return btnViewAndSave;
    }

    public JList<Customer> getListEmail() {
        return listEmail;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewAndSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Customer> listEmail;
    // End of variables declaration//GEN-END:variables
}
